cmd: ".scripts/deploy.sh"
name: "Deploy Retail"
sh: false
args:
   - "{FILE_ACTIVE_PATH}"

errorMatch:
   - <ERROR>(?<message>.+)
warningMatch:
   - <WARNING>(?<message>.+)

targets:
   PTR:
      name: "Deploy PTR"
      cmd: "sh .scripts/deploy.sh"
      args:
         - "-p"
   Classic:
      name: "Deploy Classic"
      cmd: ".scripts/deploy.sh"
      sh: false
      args:
         - "-c"
   GG-Release:
      name: "GG:Release"
      cmd: ".scripts/build.sh"
      sh: false
