cmd: "sh .scripts/deploy.sh"
name: "Deploy Retail"
args:
   - "{FILE_ACTIVE_PATH}"

errorMatch:
   - <ERROR>(?<message>.+)
warningMatch:
   - <WARNING>(?<message>.+)

targets:
   PTR:
      name: "Deploy PTR"
      cmd: "sh .scripts/deploy.sh"
      args:
         - "-p"
   Classic:
      name: "Deploy Classic"
      cmd: "sh .scripts/deloy.sh"
      args:
         - "-c"
